"""
Django settings for vmentorai project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, True)
)

# Read .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-)wvh^%4s=a+*5d4o9gj4gh9cigq44r!2odg1l0a4g700^uz_iz')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]


# Add this near other config values
GROQ_API_KEY = env("GROQ_API_KEY", default="")
DID_API_KEY = env("DID_API_KEY", default=None)

# Load D-ID API Keys for rotation
DID_API_KEYS = []
# Add the single key if it exists (backward compatibility)
if DID_API_KEY:
    DID_API_KEYS.append(DID_API_KEY)

# Add keys 1-10
for i in range(1, 11):
    key = env(f"DID_API_KEY_{i}", default=None)
    if key and key != f"your_key_{i}_here": # Ignore placeholders if they are still there
        DID_API_KEYS.append(key)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_app',
    'payment_app',
    'media_handling_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vmentorai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user_app.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'vmentorai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'vmentor_db',  # Database name you created in XAMPP
#         'USER': 'root',         # Default XAMPP MySQL username
#         'PASSWORD': '',         # Default XAMPP MySQL password is blank
#         'HOST': '127.0.0.1',    # Localhost
#         'PORT': '3306',         # Default MySQL port
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True  # Ensures timezone support is enabled
TIME_ZONE = 'Asia/Kolkata'  # Default to IST (Indian Standard Time)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'user_app.Userinfo'

# PhonePe configuration
# ... (rest of the file)
# PHONEPE_BASE_URL = "https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1"
# PHONEPE_CLIENT_ID = "TEST-M220SEDYJDCQ6_25042"
# PHONEPE_CLIENT_SECRET = "MWUyYzQ0MWYtNWFmMi00ZmEwLThhMTctMzFjNzhkODk4NmU3"
# PHONEPE_CLIENT_VERSION = 1
PHONEPE_MERCHANT_ID = env("PHONEPE_MERCHANT_ID", default="PGTESTPAYUAT86")
PHONEPE_SALT_KEY = env("PHONEPE_SALT_KEY", default="96434309-7796-489d-8924-ab56988a6076")
PHONEPE_SALT_INDEX = env("PHONEPE_SALT_INDEX", default="1")
PHONEPE_ENV = env("PHONEPE_ENV", default="SANDBOX")
PHONEPE_BASE_URL = env("PHONEPE_BASE_URL", default="https://api-preprod.phonepe.com/apis/pg-sandbox")
# Redis Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
    }
}

# Celery Configuration Options
CELERY_BROKER_URL = env("REDIS_URL", default="redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = env("REDIS_URL", default="redis://127.0.0.1:6379/1")
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
