# Generated by Django 5.1.7 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIDApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Enter your D-ID API Key here.', max_length=255, unique=True)),
                ('label', models.CharField(blank=True, help_text="Optional label (e.g., 'Key 1')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this key.')),
                ('total_credits', models.IntegerField(default=0, help_text='Manually track total credits if desired (not auto-updated).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
