# Generated by Django 5.1.7 on 2026-02-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_handling_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DIDApiKey',
        ),
    ]
